import json

with open("config.json") as f:
    CONFIG = json.load(f)

BOT_TOKEN = CONFIG["BOT_TOKEN"]
DBL_TOKEN = CONFIG["DBL_TOKEN"]
DEFAULT_PREFIX = CONFIG["DEFAULT_PREFIX"]
MONGO_URI = CONFIG["MONGO_URI"]
LOGIN_CRED = CONFIG["LOGIN_CRED"]
UPDATE_INTERVAL = CONFIG["UPDATE_INTERVAL"]
AUTH_INTERVAL = CONFIG["AUTH_INTERVAL"]
FEEDBACK_CHANNEL = CONFIG["FEEDBACK_CHANNEL"]
DEV_MODE = CONFIG["DEV_MODE"]