import json

with open("config.json") as f:
    CONFIG = json.load(f)

TOKEN = CONFIG["TOKEN"]
DEFAULT_PREFIX = CONFIG["DEFAULT_PREFIX"]
MONGO_URI = CONFIG["MONGO_URI"]
LOGIN_CRED = CONFIG["LOGIN_CRED"]
UPDATE_INTERVAL = CONFIG["UPDATE_INTERVAL"]
AUTH_INTERVAL = CONFIG["AUTH_INTERVAL"]
FEEDBACK_CHANNEL = CONFIG["FEEDBACK_CHANNEL"]